"use strict";

const FilterConstants = {
  UPDATE_BOUNDS: "UPDATE_BOUNDS",
  UPDATE_TIME_SLOT: "UPDATE_TIME_SLOT",
  UPDATE_DATE: "UPDATE_DATE",
  UPDATE_NAME: "UPDATE_NAME",
  UPDATE_GUESTS: "UPDATE_GUESTS",
  CLEAR_FILTERS: "CLEAR_FILTERS",
  SET_FILTER: "SET_FILTER",
  UNSET_FILTER: "UNSET_FILTER"
};

module.exports = FilterConstants;
