"use strict";

const FilterConstants = {
  UPDATE_BOUNDS: "UPDATE_BOUNDS",
  UPDATE_TIME_SLOT: "UPDATE_TIME_SLOT",
  UPDATE_DATE: "UPDATE_DATE",
  UPDATE_NAME: "UPDATE_NAME",
  UPDATE_GUEST_COUNT: "UPDATE_GUEST_COUNT",
  CLEAR_FILTERS: "CLEAR_FILTERS",
  FILTER_FAVORITES: "FILTER_FAVORITES",
  SET_FILTER: "SET_FILTER",
  UNSET_FILTER: "UNSET_FILTER",

  DEFAULT_TIME_SLOT: 38,
  DEFAULT_GUEST_COUNT: 2
};

module.exports = FilterConstants;
